# Generated by Django 2.1 on 2019-07-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('View_no', models.IntegerField()),
                ('Audit_item', models.CharField(max_length=254)),
                ('Checklist_type', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Date', models.DateTimeField()),
                ('Loan_No', models.IntegerField()),
                ('Borrower_lname', models.CharField(max_length=254)),
                ('State', models.CharField(max_length=254)),
                ('File_process', models.IntegerField()),
                ('File_status', models.CharField(max_length=254)),
                ('Proc_userid', models.CharField(max_length=254)),
                ('Proc_sdate', models.DateTimeField()),
                ('Proc_edate', models.DateTimeField()),
                ('Qc_process', models.IntegerField()),
                ('Qc_userid', models.CharField(max_length=254)),
                ('Qc_sdate', models.DateTimeField()),
                ('Qc_edate', models.DateTimeField()),
                ('Checklist', models.CharField(max_length=254)),
            ],
        ),
    ]
