# Generated by Django 2.1 on 2019-07-24 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('View_no', models.IntegerField()),
                ('Audit_item', models.CharField(max_length=254)),
                ('Checklist_type', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='docinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tdfileid', models.IntegerField(null=True)),
                ('Loan_no', models.IntegerField(null=True)),
                ('Borrower_lname', models.CharField(max_length=254, null=True)),
                ('State', models.CharField(max_length=254, null=True)),
                ('View_no', models.IntegerField(null=True)),
                ('Checklist', models.CharField(max_length=254, null=True)),
                ('Proc_status', models.CharField(max_length=254, null=True)),
                ('Proc_comments', models.CharField(max_length=254, null=True)),
                ('Qc_status', models.CharField(max_length=254, null=True)),
                ('Qc_comments', models.CharField(max_length=254, null=True)),
                ('Checklist_type', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Date', models.DateTimeField()),
                ('Sr_No', models.IntegerField()),
                ('Loan_No', models.IntegerField()),
                ('MM_Loan', models.CharField(max_length=254)),
                ('Borrower_lname', models.CharField(max_length=254)),
                ('File_process', models.IntegerField(blank=True, default=0, null=True)),
                ('File_note', models.CharField(blank=True, max_length=254, null=True)),
                ('File_status', models.CharField(blank=True, max_length=254, null=True)),
                ('Proc_userid', models.CharField(blank=True, max_length=254, null=True)),
                ('Proc_sdate', models.DateTimeField(blank=True, null=True)),
                ('Proc_edate', models.DateTimeField(blank=True, null=True)),
                ('Qc_process', models.IntegerField(blank=True, null=True)),
                ('Qc_userid', models.CharField(blank=True, max_length=254, null=True)),
                ('Qc_sdate', models.DateTimeField(blank=True, null=True)),
                ('Qc_edate', models.DateTimeField(blank=True, null=True)),
                ('Process_Type', models.CharField(max_length=254)),
                ('Checklist', models.CharField(max_length=254)),
                ('File_name', models.CharField(max_length=254)),
                ('Priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=120)),
                ('Delete_date', models.DateTimeField(blank=True, null=True)),
                ('Role', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
