# Generated by Django 2.1 on 2019-08-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0002_userprofile_sample_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='docinfo',
            name='File_name',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfo',
            name='Sr_No',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
