# Generated by Django 2.1 on 2019-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0002_auto_20190709_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='File_process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='File_status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='Proc_edate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='Proc_sdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='Proc_userid',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='Qc_edate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='Qc_process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='Qc_sdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='Qc_userid',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
