# Generated by Django 2.1 on 2019-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0003_auto_20190709_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='docinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tdfileid', models.IntegerField()),
                ('Loan_no', models.IntegerField()),
                ('Borrower_lname', models.CharField(max_length=254)),
                ('State', models.CharField(max_length=254)),
                ('View_no', models.IntegerField()),
                ('Checklist', models.CharField(max_length=254)),
                ('Proc_status', models.CharField(max_length=254)),
                ('Proc_comments', models.CharField(max_length=254)),
                ('Qc_status', models.CharField(max_length=254)),
                ('Qc_comments', models.CharField(max_length=254)),
                ('Checklist_type', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='File_process',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
