# Generated by Django 2.1 on 2019-07-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0004_auto_20190709_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docinfo',
            name='Borrower_lname',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Checklist',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Checklist_type',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Loan_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Proc_comments',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Proc_status',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Qc_comments',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Qc_status',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='State',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Tdfileid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='View_no',
            field=models.IntegerField(null=True),
        ),
    ]
