# Generated by Django 2.1 on 2019-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processing', '0007_fileinfo_file_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='File_note',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
